[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5"
rodio = "0.17"
egui_plot = "0.24"
rustfft = "6"
winapi = { version = "0.3", features = ["winuser"] }
eframe = { version = "0.24", features = ["persistence", "glow", "egui_plot"] }
